Repository blackportal-ai/delta, pull requests merged in 2024-12, with the labels that each got.

#40 Adding optimization for performance and cleanup
  delta/Cargo.toml
  delta/src/activations/relu.rs
  delta/src/common/shape.rs
  delta/src/data/mnist.rs
  delta/src/data/mod.rs
  delta/src/data/test_dataset.rs
  delta/src/losses/cross_entropy.rs
  delta/src/losses/sparse_categorical_cross_entropy.rs
  delta/src/neuralnet/models/sequential.rs
Labels: feature

#41 Updating core.yml workflow
  .github/workflows/core.yml
Labels: feature

#43 Improving sequential model output while training
  delta/src/neuralnet/models/sequential.rs
Labels: feature

#46 Resolves #32 - Save model
  delta/Cargo.toml
  delta/src/common/activation.rs
  delta/src/common/layer.rs
  delta/src/common/tensor_ops.rs
  delta/src/neuralnet/layers/dense.rs
  delta/src/neuralnet/models/sequential.rs
  examples/image_classification/mnist/src/main.rs
Labels: feature

#52 Helper func adam
  delta/src/optimizers/adam.rs
Labels: feature

#75 Fix split_at to allow dynamic shapes
  delta/src/common/tensor_ops.rs
Labels: bug

#130 Fix unused dependencies
  delta/Cargo.toml
Labels: dependencies

#144 Fix unused dependencies
  delta_bench/Cargo.toml
Labels: dependencies

#148 Adding benches
  delta/src/common/mod.rs
  delta_bench/Cargo.toml
  delta_bench/src/adam_benchmark.rs
  delta_bench/src/benchmark.rs
  delta_bench/src/main.rs
Labels: feature

#149 Fixing completion of samples for benchmark_adam_optimizer_large
  delta_bench/src/adam_benchmark.rs
Labels: bug
